import type {Metadata} from 'next'
import './globals.css'
import localFont from 'next/font/local'

// Font files can be colocated inside of `app`
const optima = localFont({
  src: './fonts/optima/VNF-Optima.woff2',
  display: 'swap',
  variable: '--font-optima',
})

const helvetica = localFont({
  src: [
    {
      path: './fonts/helvetica/HelveticaNeue-UltraLight.woff2',
      weight: '100',
      style: 'normal',
    },
    {
      path: './fonts/helvetica/HelveticaNeue-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/helvetica/HelveticaNeue-Normal.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/helvetica/HelveticaNeue-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/helvetica/HelveticaNeue-CondensedBold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/helvetica/HelveticaNeue-CondensedBlack.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-helvetica',
})

const aisaviva = localFont({
  src: [
    {
      path: './fonts/vivatravel/AsiaVivaTravel-Regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-aisaviva',
})

export const metadata: Metadata = {
  title: 'Asiaviva Travel',
  description: 'Generated by Dev Okhub',
}

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${helvetica.className} ${helvetica.variable} ${optima.variable} ${aisaviva.variable}`}
      >
        {children}
      </body>
    </html>
  )
}
