import localFont from 'next/font/local'
import {Metadata} from 'next'

import './globals.css'
import Header from '../layout/header/Header'

import {Karla} from 'next/font/google'

const Sackers = localFont({
  src: [
    {
      path: './fonts/Sackers_Gothic_Font/sackersgothicstd-medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Sackers_Gothic_Font/sackersgothicstd-heavy.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Sackers_Gothic_Font/sackersgothicstd-light.otf',
      weight: '300',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-scakers',
})

const Beautique = localFont({
  src: [
    {
      path: './fonts/Beautique_Display_Condensed/BeautiqueDisplayCondensed-Regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-beautique',
})

const karla = Karla({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-karla',
})

export const metadata: Metadata = {
  title: 'Jenho',
  description: 'Generated by Dev Finn',
}

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
}

export default function RootLayout({
  children,
  test,
}: Readonly<{
  children: React.ReactNode
  test: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning={true}
    >
      <body
        className={`${Sackers.variable} ${karla.variable} ${Beautique.variable} ${Sackers.className}`}
      >
        <Header />
        {test}
        {children}
      </body>
    </html>
  )
}
